### ISSUE TITLE
Support Visual C++/Visual Studio toolchain

### ISSUE THREAD

**Issue by spencels** [google/jsonnet#300] opened 2017-02-11 11:13 UTC
Jsonnet and libjsonnet/libjsonnet++ should be buildable with the Visual C/C++ (VC/VC++) compiler. The project should include build files for a tool that integrates well with Visual Studio (VS) such as MSBuild, CMake, or NMake.

## Rationale

Microsoft's Visual C/C++ compiler is widely used on Windows. It's bundled with and integrated with Visual Studio, probably the most widely used IDE for C/C++ development on Windows. A small amount of development would give a wide community of developers easy access to Jsonnet.

Jsonnet currently supports Windows builds using Cygwin and MinGW, using make as a build system. These don't integrate well with VS. Cygwin .so libraries can't be used by other Windows development tools. VS can use DLLs and possibly even object files from MinGW's gcc, but not g++ as name mangling works differently. VS also doesn't integrate with the GNU toolchain: no make or gcc support (although there may be plugins for this). Developers wishing to use Jsonnet in a VC++ project must either forgo advanced IDE features like code search and debugging, or manually create their own project file.

VS is also the de facto IDE for .NET development. Supporting VS/VC++ will make writing and maintaining C#/.NET bindings for Jsonnet easier in the future.

**Comment by thefoojoo** [comment] 2017-02-11 11:13
I'm looking into this in my spare time, please assign to me if no one else is working on it.

**Comment by sparkprime** [comment] 2017-02-17 02:43
In principle, the code is all standard.  In practice, it may have bugs that only show up on VC.  I'm happy to accept PRs to fix these bugs :)  In 2014, I tried compiling Jsonnet with Visual Studio Express 12, but it crashed the compiler.  It is definitely worth trying it with a more modern MSVC.  There is this fork adding VC support which is quite old, but might provide some useful insight https://github.com/tyler-elric/jsonnet

Having yet another build system would be kind of a pain.  However I can't think of a better solution.  Is there some way of running regression tests on travis against VC?  The typical problem is that someone renames a header or adds a file or whatever, and only n-1 of the build scripts get updated, breaking one of the platforms.  Currently we have BUILD, Makefile, setup.py (for pypi).

**Comment by thefoojoo** [comment] 2017-02-17 07:16
I was able to compile Jsonnet and its tests without modification using VS2015. The question remains of what build system to use.

One build system option is to replace Make with [CMake](https://cmake.org/). It's a meta build system that generates targets for other build systems: Make, Visual Studio, Eclipse, etc. It also has features and plugins for other stuff like cloning external repos, copying files, and running external commands.

Bazel (BUILD) has Windows support but it's in beta at the moment ([full support by 2017](https://bazel.build/roadmap.html)). But I'm guessing they won't support MSVC++ so that doesn't address this issue.

[Travis does not seem to support VC++](https://docs.travis-ci.com/user/languages/cpp#CI-environment-for-C%2B%2B-Projects), which is unfortunate.

I think CMake is the best option, because it gives Jsonnet compatibility with a [ton of build systems](https://cmake.org/cmake/help/v3.0/manual/cmake-generators.7.html#command-line-build-tool-generators). If that won't work, I'll just hand-create Visual Studio targets and hope people submit bug reports as stuff breaks.

**Comment by sparkprime** [comment] 2017-02-17 16:14
Either cmake or hand-written vcxproj is fine with me

**Comment by sbarzowski** [comment] 2020-05-22 10:41
We have some VS files in the repo (#344 stuff) I'm going to close this issue..

**Closed by sbarzowski** 2020-05-22 10:41 UTC
