### ISSUE TITLE
decimal point issue

### ISSUE THREAD

**Issue by amirmasoudabdol** [google/jsonnet#604] opened 2019-02-12 09:13 UTC
This is probably a noob question but I'm trying to generate a JSON through a _top-level arguments_ and one of my parameters is a double. The problem is that `jsonnet` round `0.05` to `0.050000000000000003`. As far as I know, JSON is not going to do well when it comes to numeric values, but is there a workaround that I can get my `0.05` as numeric. I'm aware that I can format it to a string value and then deal with it later, but that's not a nice solution for me.

Thanks in advance,
Amir.

**Comment by sbarzowski** [comment] 2019-02-12 11:59
I think it has come up already, but I can't find the issue. Anyway the thing is that currently Jsonnet always outputs 17 digits for non-integer numbers. This is the minimal number of digits (in general) which guarantees specific 64-bit floating point value.

Of course some numbers have shorter representations. I think we should use them (e.g. `0.050000000000000003 == 0.05`). I'm not sure what is the right way to do it.

**Comment by amirmasoudabdol** [comment] 2019-02-12 12:54
Maybe something like `std.praseToInt` but with an extra parameter to specify the number of digits? So, `std.parseToDouble(x, n)`. 🤷‍♂️

**Comment by sparkprime** [comment] 2019-02-25 13:05
See discussion here https://github.com/google/jsonnet/issues/558

**Comment by sparkprime** [comment] 2019-02-25 16:47
Closing as a duplicate (the issue is a valid one, though!)

**Closed by sparkprime** 2019-02-25 16:47 UTC
Labels: duplicate
