### ISSUE TITLE
cannot use jsonnet to base64 keystore

### ISSUE THREAD

**Issue by bernadinm** [google/jsonnet#738] opened 2019-12-12 18:56 UTC
When working with certificates and Kubernetes, it would be great to use jsonnet to be able to base64 encode files that are binaries or allow a new function to support a function as Kubernetes support binarydata when using ConfigMaps. Currently I have to base64 the file within an automated script as a workaround for the time being.

Here is how to successfully reproduce this:

### Reproduce Steps
```
openssl req -new -x509 -keyout test-ca-1.key -out test-ca-1.crt -days 365 -subj '/CN=ca1.test.example.com/OU=TEST/O=TESTING/L=PaloAlto/S=Ca/C=US' -passin pass:test -passout pass:test
echo yes | keytool -importcert -keystore gate.jks -alias ca -file test-ca-1.crt -storepass 1234567
jsonnet -e 'local test = importstr "./gate.jks"; std.base64(test)'
```

### Error

```
RUNTIME ERROR: Can only base64 encode strings / arrays of single bytes.
	std.jsonnet:1110:7-71	function <anonymous>
	<cmdline>:1:38-54
```

### Workaround Steps
```
base64 < gate.jks > gate.jks.base64decoded
```

### Result
```
cut -c -5 gate.jks.base64decoded
MIIEX
```

**Comment by sbarzowski** [comment] 2019-12-13 00:14
The root cause of the problems here is that the strings in Jsonnet are unicode strings. This has two consequences:
1) Strings should be converted to desired encoding, before applying base64 (which is defined on byte sequences). For example `std.base64(std.encodeUTF8(test))` will make the error go away in your case.
2) `importstr` expects UTF8 contents of the file. You may not get the same bytes in the output after re-encoding it, if it was not valid UTF8. This is a bigger problem. See: #739.

**Comment by sparkprime** [comment] 2020-02-28 23:42
This is a feature request for `importbin` or some similar functionality, right?

**Comment by sbarzowski** [comment] 2020-02-29 01:02
Yes, that would solve the problem here. This is tracked in #739.

**Comment by sbarzowski** [comment] 2020-05-02 23:30
Since this is tracked by #739, I'm going to close this one.

**Closed by sbarzowski** 2020-05-02 23:30 UTC
