### ISSUE TITLE
[Website] Interactive tutorial - "TypeError: Module.UTF8ToString is not a function"

### ISSUE THREAD

**Issue by sbarzowski** [google/jsonnet#768] opened 2020-02-09 23:54 UTC
Whenever I change the code on the website the following error shows up:
```
TypeError: Module.UTF8ToString is not a function"
```
I have recently updated the website, but the commit does not touch the libjsonnet.js. 

@sparkprime Do you have any ideas for what it might be, or how to fix it? Should I revert (but then the stdlib docs will be really out of date).

**Comment by buremba** [comment] 2020-02-21 10:17
The interactive editor still doesn't work. The unofficial binding is too big (< 4MB) while the Jsonnet compiler on the website (https://jsonnet.org/js/libjsonnet.js) is just 330kb. How is that possible, any ideas?

**Comment by ivan4th** [comment] 2020-02-21 13:53
FYI, it can be fixed with the following bookmarklet:
```
javascript:void(Module.UTF8ToString=UTF8ToString)
```
Usable as an interim solution for playing around with the examples till the website is fixed.

**Comment by sparkprime** [comment] 2020-02-23 22:14
So this emscripten library function is nolonger accessed through Module (or never was, and luckily worked until some new version)?

**Comment by buremba** [comment] 2020-02-24 00:00
This commit looks like the cause: https://github.com/google/jsonnet/commit/c323f5ce5b8aa663585d23dc0fb94d4b166c6f16#diff-f1185dfe3c71b3025eaf7ba31336a40bL39

When I revert it to `Pointer_stringify` it works as expected.

**Comment by sbarzowski** [comment] 2020-02-24 08:46
Weird. `Pointer_stringify` was deprecated in favor of `UTF8ToString`.

**Comment by FranklinYu** [comment] 2020-02-27 20:52
`UTF8ToString` is [in preamble](https://emscripten.org/docs/api_reference/preamble.js.html#UTF8ToString), so I guess it should be called directly.

**Comment by sparkprime** [comment] 2020-02-28 22:35
I tried to rebuild it locally, but got this!
```
Error: abort(Assertion failed: you need to wait for the runtime to be ready (e.g. wait for main() to be called)) at Error
    at jsStackTrace (http://localhost:8200/js/libjsonnet.js:47:16244)
    at stackTrace (http://localhost:8200/js/libjsonnet.js:47:16412)
    at abort (http://localhost:8200/js/libjsonnet.js:47:13259)
    at assert (http://localhost:8200/js/libjsonnet.js:47:1647)
    at Module._jsonnet_make (http://localhost:8200/js/libjsonnet.js:47:97850)
    at ccall (http://localhost:8200/js/libjsonnet.js:47:2575)
    at http://localhost:8200/js/libjsonnet.js:47:2737
    at jsonnet_evaluate_snippet_wrapped (http://localhost:8200/js/demo.js:60:12)
    at http://localhost:8200/js/demo.js:382:20
    at http://localhost:8200/js/demo.js:287:9
```

**Comment by sparkprime** [comment] 2020-02-28 23:00
That seemed to be caused by another error `"mb is not defined"`

However... If I build without -Os the problem goes away.  I'm going to push the site with this new js file.

**Comment by sparkprime** [comment] 2020-02-28 23:03
I still get these but assuming they are benign

```
wasm2js: warning: global scope may be colliding with other scope: bool_20std____2__operator___char_2c_20std____2__char_traits_char__2c_20std____2__allocator_char__20__28std____2__basic_string_char_2c_20std____2__char_traits_char__2c_20std____2__allocator_char__20__20const__2c_20char_20const__29
wasm2js: warning: global scope may be colliding with other scope: bool_20std____2__operator___char_2c_20std____2__char_traits_char__20__28std____2__istreambuf_iterator_char_2c_20std____2__char_traits_char__20__20const__2c_20std____2__istreambuf_iterator_char_2c_20std____2__char_traits_char__20__20const__29
wasm2js: warning: global scope may be colliding with other scope: bool_20std____2__operator___wchar_t_2c_20std____2__char_traits_wchar_t__20__28std____2__istreambuf_iterator_wchar_t_2c_20std____2__char_traits_wchar_t__20__20const__2c_20std____2__istreambuf_iterator_wchar_t_2c_20std____2__char_traits_wchar_t__20__20const__29
warning: Output contains some very large functions (5497 lines in $28anonymous_20namespace_29__Interpreter__evaluate_28AST_20const__2c_20unsigned_20int_29), consider building source files with -Os or -Oz)
```

**Comment by sparkprime** [comment] 2020-02-28 23:15
Well it works again for me.  Reopen the bug if there's still issues.  Thanks for the reports and workarounds in the meantime!

**Closed by sparkprime** 2020-02-28 23:15 UTC

**Comment by sparkprime** [comment] 2020-02-28 23:37
For the record:
```
dcunnin@dcunnin:~$ em++ --version
emcc (Emscripten gcc/clang-like replacement) 1.39.8 (commit 1458145cf4f3db0fb548343e6acab267eef8e4ef)
Copyright (C) 2014 the Emscripten authors (see AUTHORS.txt)
This is free and open source software under the MIT license.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by FranklinYu** [comment] 2020-02-29 01:52
Fix verified on Chrome, Debian. Thanks!
