### ISSUE TITLE
Feature Request: yaml without double quotes (std.manifestYamlDoc)

### ISSUE THREAD

**Issue by Ghost---Shadow** [google/jsonnet#717] opened 2019-10-10 05:20 UTC
std.manifestYamlDoc generates an yaml like

```yml
"a":"foo"
"b":"bar"
"c":"awesome sauce"
```

which is a valid yaml but it breaks my vscode syntax highlighter.

Can you add a flag which generates like so

```yml
a: foo
b: bar
c: 'awesome sauce'
```

Which is much easier to read IMO

**Comment by seh** [comment] 2019-10-10 12:30
Also see #682 and several others that I can’t find at the moment. I recall we discussed the escaping rules again the last time that @sparkprime fixed a problem with indentation when serializing arrays.

**Comment by Ghost---Shadow** [comment] 2019-10-23 03:54
I found a temporary solution

```sh
DIR=$1

for y in ${DIR}/*.yml
do
  yq -y '.' "${y}" > "${y}.tmp"
  mv "${y}.tmp" "${y}"
done
```
You can run it like `my_script.sh ./my_dir`

**Comment by sbarzowski** [comment] 2020-05-02 23:34
I'm going to close this as a duplicate of #682.

**Closed by sbarzowski** 2020-05-02 23:34 UTC
Labels: enhancement

**Comment by manji-0** [comment] 2023-05-11 12:18
> I found a temporary solution
> 
> DIR=$1
> 
> for y in ${DIR}/*.yml
> do
>   yq -y '.' "${y}" > "${y}.tmp"
>   mv "${y}.tmp" "${y}"
> done
> You can run it like my_script.sh ./my_dir

Today, there is a simpler solution.

```
DIR=$1

for y in ${DIR}/*.yml
do
  yq -P -i ${y}
done
```

Also, it is faster to output in json and then convert in yq than to use `std.manifestYamlDoc`.

```
jsonnet foo.jsonnet -o foo.json
yq -o yaml -P foo.json > foo.yml
rm foo.json
```

This was verified with `yq (https://github.com/mikefarah/yq/) version v4.33.3`.
