### ISSUE TITLE
Unrecognised conversion type - Impossible to debug

### ISSUE THREAD

**Issue by ghostsquad** [google/jsonnet#758] opened 2020-01-17 06:43 UTC
I just got this error, and I'm completely baffled by how to begin debugging.

```
RUNTIME ERROR: Unrecognised conversion type: {
	<std>:419:11-53	function <parse_conv_type>
	<std>:432:23-52	thunk <ctype> from <function <parse_code>>
	<std>:434:14-19
	<std>:453:28-31	thunk from <function <parse_codes>>
	<std>:453:11-57	function <parse_codes>
	<std>:457:19-46	thunk <codes> from <function <anonymous>>
	<std>:752:24-29	thunk from <function <anonymous>>
	<std>:710:26-31	thunk from <function <format_codes_obj>>
	<std>:710:15-32	function <format_codes_obj>
	<std>:752:7-43	function <anonymous>
	<std>:227:7-23	function <anonymous>
	During manifestation
2020/01/16 22:40:43 exit status 1
```

**Comment by ghostsquad** [comment] 2020-01-17 06:45
looks like this might be related to https://github.com/google/go-jsonnet/issues/249

**Comment by sbarzowski** [comment] 2020-01-17 08:14
It looks like you have a format string containing "%{" based on the error message and the stack trace.  It sucks that the stack trace doesn't include the actual location in your code.

**Comment by sbarzowski** [comment] 2020-01-17 08:18
Yeah, it seems very similar to google/go-jsonnet#249 (missing type specifier). Have you perhaps used `{}` instead of `()` in your format string?

**Comment by ghostsquad** [comment] 2020-01-17 15:34
After finding the similar issue I linked, I searched for `%` and found the
offending pieces.

Are better stack traces on the horizon? At least maybe for a go-jsonnet?

Cheers,
Wes

**Comment by sbarzowski** [comment] 2020-01-17 16:55
> Are better stack traces on the horizon? At least maybe for a go-jsonnet?

It's on the (pretty long) list of things I would like to do. And it shouldn't be even very hard, but requires digging into the internals quite a bit.

**Comment by sbarzowski** [comment] 2020-01-17 16:56
BTW examples really help for this sort of thing, so issues like "here's a concrete, runnable code snippet for which the stack trace sucks" are **very** welcome.

**Comment by ghostsquad** [comment] 2020-01-17 18:25
It was indeed a string interpolation problem. I had `"%(foo)"` instead of `"%(foo)s"`

**Comment by sparkprime** [comment] 2020-02-28 23:18
Since the issue is resolved and we don't have a repro case for improving stack traces, I'm going to close it.

**Closed by sparkprime** 2020-02-28 23:18 UTC
