### ISSUE TITLE
Support `1 in [1, 2, 3]`

### ISSUE THREAD

**Issue by sparkprime** [google/jsonnet#667] opened 2019-06-03 17:39 UTC

**Comment by seh** [comment] 2019-06-03 18:57
Would this assume that the array is a set (using binary search), or would it use linear search?

**Comment by sbarzowski** [comment] 2019-06-03 20:11
I think linear search is safer here. It may be really confusing otherwise.

**Comment by seh** [comment] 2019-06-03 20:13
I think we should document that this is _not_ sugar for `std.setMember`, and vice versa, that `std.setMember` is not implemented in terms of this.

**Comment by sbarzowski** [comment] 2019-11-22 16:29
Duplicate of #513.

**Closed by sbarzowski** 2019-11-22 16:29 UTC
Labels: duplicate
